//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shop2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public long id_order { get; set; }
        public System.DateTime date_order { get; set; }
        public long id_customer { get; set; }
        public string Address { get; set; }
        public long id_product { get; set; }
        public int count_product { get; set; }
        public long id_deliveryman { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Deliveryman Deliveryman { get; set; }
        public virtual Product Product { get; set; }
    }
}
